
name: Update Version Number
on:
  release:
    types: [published]

jobs:
  update-version-number:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          version-regexp: '\d+.\d+.\d+'
          branch-name: 'main'
